version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: "/ferramentas/laboratorio_capacidade"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: "/ferramentas/laboratorio_significado"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
