#!/usr/bin/env node
// Ensaio integral: dois clusters locais, dados fictícios, nenhum acesso à produção.
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile, rm, stat } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { capture, restore, localCluster } from './backup_nativo.mjs';

const bin = path.join(os.homedir(), '.local/share/datadrobe-tools/Postgres.app/Contents/Versions/17/bin');
const root = await mkdtemp(path.join(os.tmpdir(), 'dd-backup-teste-'));
const origem = await localCluster(bin);
try {
  await origem.exec(`
    CREATE ROLE anon NOLOGIN;
    CREATE ROLE authenticated NOLOGIN;
    CREATE ROLE service_role NOLOGIN BYPASSRLS;
    CREATE SCHEMA auth;
    CREATE SCHEMA storage;
    CREATE SCHEMA supabase_migrations;
    CREATE TABLE auth.users (id uuid PRIMARY KEY, email text UNIQUE);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    CREATE TABLE public.pecas (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id uuid REFERENCES auth.users(id),
      nome text NOT NULL, atributos jsonb, criado_em timestamptz DEFAULT now(),
      CONSTRAINT nome_preenchido CHECK (length(nome)>0)
    );
    CREATE UNIQUE INDEX pecas_nome_unique ON public.pecas(nome);
    INSERT INTO auth.users VALUES ('00000000-0000-0000-0000-000000000001', 'fixture@example.invalid');
    INSERT INTO public.pecas(user_id,nome,atributos)
      SELECT '00000000-0000-0000-0000-000000000001', 'Peça çã 🎨 '||g||E'\\nsegunda linha', jsonb_build_object('i',g,'texto',repeat('á🎨',80))
      FROM generate_series(1,12000) g;
    ALTER TABLE public.pecas ENABLE ROW LEVEL SECURITY;
    CREATE POLICY propria ON public.pecas TO authenticated USING (user_id = auth.uid());
    GRANT USAGE ON SCHEMA public,auth TO authenticated;
    GRANT SELECT,INSERT ON public.pecas TO authenticated;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anon;
    CREATE VIEW public.titulos WITH (security_invoker=true) AS SELECT id,nome FROM public.pecas;
    CREATE MATERIALIZED VIEW public.total AS SELECT count(*) AS n FROM public.pecas;
    CREATE FUNCTION public.normalizar() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$ BEGIN NEW.nome := btrim(NEW.nome); RETURN NEW; END $$;
    CREATE TRIGGER normalizar BEFORE INSERT ON public.pecas FOR EACH ROW EXECUTE FUNCTION public.normalizar();
    CREATE TABLE storage.objects (id uuid PRIMARY KEY, name text, owner uuid REFERENCES auth.users(id));
    INSERT INTO storage.objects VALUES ('00000000-0000-0000-0000-000000000002','fixture/foto.jpg','00000000-0000-0000-0000-000000000001');
    CREATE TABLE supabase_migrations.schema_migrations (version text PRIMARY KEY);
    INSERT INTO supabase_migrations.schema_migrations VALUES ('fixture-1');
    -- Reproduz um default curto; somente as conexões do backup devem sobrepô-lo.
    ALTER ROLE postgres SET statement_timeout = '1ms';
  `);
  const dest = path.join(root, 'dump');
  const manifest = await capture(bin, origem.c, dest);
  assert.equal(manifest.rows['public.pecas'].count, 12000);
  assert.equal(manifest.bootstrap.read_session.statement_timeout,'10min');
  assert.equal(manifest.bootstrap.read_session.default_transaction_read_only,'on');
  assert.equal((await stat(path.join(dest,'banco.dump'))).mode & 0o777, 0o600);
  assert.equal((await stat(dest)).mode & 0o777, 0o700);
  const report = await restore(bin, dest);
  assert.equal(report.result, 'VERIFICADO_NO_ESCOPO_DECLARADO');
  console.log('ok 1: dump real + restore real + Unicode/COPY + FKs/RLS/índices/funções');
  console.log('ok 1b: timeout curto herdado é sobreposto somente na sessão de leitura');
  const original = await readFile(path.join(dest,'manifesto.json'),'utf8');
  const wrong = JSON.parse(original);
  wrong.rows['public.pecas'].count++;
  await writeFile(path.join(dest,'manifesto.json'),JSON.stringify(wrong));
  await assert.rejects(restore(bin,dest),/Dados divergentes em public.pecas/);
  console.log('ok 2: dado divergente reprova restauração');
  wrong.archive_sha256 = '0'.repeat(64);
  await writeFile(path.join(dest,'manifesto.json'),JSON.stringify(wrong));
  await assert.rejects(restore(bin,dest),/SHA-256/);
  console.log('ok 3: archive adulterado reprova antes da restauração');
  console.log('ENSAIO LOCAL VERDE — não equivale a backup de produção.');
} finally {
  await origem.close();
  await rm(root,{recursive:true});
}
