#!/usr/bin/env node
/**
 * Ensaio do roteiro da etapa 1 num PostgreSQL 17.10 descartável.
 *
 * Cada passo é executado pelo MESMO executor que rodaria em produção
 * (`passo.mjs`), como subprocesso, conectado como um papel que imita o
 * `postgres` do Supabase: sem superusuário, dono das tabelas de `public`,
 * membro de `pg_read_all_stats` e `pg_monitor`, e sem ser dono do log do
 * pg_cron -- onde só tem MAINTAIN e DELETE, como em produção.
 *
 * O que ele prova:
 *   - o ensaio (sem --executar) não escreve nada;
 *   - cada ação encolhe o alvo e não perde nenhuma linha;
 *   - cada pré-condição aborta ANTES da ação quando deve;
 *   - o TRUNCATE alternativo vem desarmado;
 *   - VACUUM sem MAINTAIN é pego pela checagem de encolhimento.
 *
 * O que ele NÃO prova: tempo e espaço de produção. As tabelas daqui são
 * pequenas; o disco é outro. Os números de produção vêm do inventário.
 */
import { spawn, spawnSync } from 'node:child_process';
import { once } from 'node:events';
import { chmod, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const AQUI = path.dirname(fileURLToPath(import.meta.url));
const REPOSITORIO = path.resolve(AQUI, '../..');
const MIGRATIONS = path.join(REPOSITORIO, 'supabase/migrations');
const AMBIENTE = { PATH: '/usr/local/bin:/usr/bin:/bin', LANG: 'C', LC_ALL: 'C', TZ: 'UTC' };
const MODULOS = [
  path.join(os.homedir(), '.canario/laboratorio-capacidade/node_modules'),
  path.join(os.homedir(), '.canario/laboratorio-significado/node_modules'),
].find(c => { try { createRequire(path.join(c, 'index.js')).resolve('pg'); return true; } catch { return false; } });

let falhas = 0;
function conferir(condicao, mensagem) {
  if (condicao) console.log(`ok  ${mensagem}`);
  else { console.log(`FALHOU  ${mensagem}`); falhas += 1; }
}

async function main() {
  if (!MODULOS) throw new Error('Instale o laboratório de capacidade (ver README).');
  const require = createRequire(path.join(MODULOS, 'index.js'));
  const b = require(`@embedded-postgres/${process.platform}-${process.arch}`);
  const pg = require('pg');
  for (const n of ['initdb', 'postgres', 'pg_ctl']) await chmod(b[n], 0o755);

  const raiz = await mkdtemp(path.join(os.tmpdir(), 'datadrobe-rot-'));
  await chmod(raiz, 0o700);
  const dados = path.join(raiz, 'd');
  const sock = path.join(raiz, 's');
  await mkdir(sock, { mode: 0o700 });
  // `trust` só no socket, numa pasta 0700 deste processo: é o que deixa o
  // executor conectar como papel comum sem senha no laboratório.
  spawnSync(b.initdb, ['-D', dados, '-U', 'lab', '--auth=trust', '--no-locale',
    '--encoding=UTF8'], { env: AMBIENTE });
  const servidor = spawn(b.postgres, ['-D', dados, '-k', sock, '-h', '',
    '-c', 'listen_addresses=', '-c', 'fsync=off', '-c', 'autovacuum=off'],
  { env: AMBIENTE, stdio: 'ignore' });

  const conectar = async (usuario) => {
    for (let t = 0; t < 50; t += 1) {
      const c = new pg.Client({ host: sock, user: usuario, database: 'postgres' });
      // Sem isto, o desligamento do cluster no `finally` derruba o processo
      // antes de ele imprimir o erro que levou até lá.
      c.on('error', () => {});
      try { await c.connect(); return c; } catch { await new Promise(r => setTimeout(r, 200)); }
    }
    throw new Error('o cluster não aceitou conexão');
  };
  const admin = await conectar('lab');

  const passo = (arquivo, ...extra) => {
    const r = spawnSync(process.execPath, [path.join(AQUI, 'passo.mjs'),
      path.join(AQUI, arquivo), '--socket', sock, '--usuario', 'operador',
      '--senha-vazia', '--modulos', MODULOS, ...extra], { encoding: 'utf8' });
    return { codigo: r.status, saida: `${r.stdout}${r.stderr}` };
  };
  const tamanho = async (rel) => Number((await admin.query(
    'select pg_total_relation_size($1::regclass) as n', [rel])).rows[0].n);
  const linhas = async (rel) => Number((await admin.query(
    `select count(*) as n from ${rel}`)).rows[0].n);

  try {
    // Papéis no formato de produção.
    await admin.query(`
      create role operador login in role pg_read_all_stats, pg_monitor;
      create role admin_da_plataforma nologin;
      grant create on schema public to operador;
      create schema cron authorization admin_da_plataforma;
      grant usage on schema cron to operador;`);

    // Tabelas de public, criadas pelo operador -- ele é o dono, como o
    // `postgres` é em produção.
    const op = await conectar('operador');
    await op.query(`
      create table public.motor_execucoes (execucao uuid, status text,
        iniciado_em timestamptz, concluido_em timestamptz, resultado jsonb);
      create table public.series_semanais (id bigint generated by default as identity primary key,
        termo_id text, segmento text, fonte text, semana date, valor_bruto numeric,
        z numeric, n_amostra int, meta jsonb, unique (termo_id, segmento, fonte, semana))
        with (fillfactor = 70);
      create table public.indices_semanais (id bigint generated by default as identity primary key,
        termo_id text, segmento text, semana date, indice numeric, meta jsonb,
        unique (termo_id, segmento, semana)) with (fillfactor = 70);
      create table public.artigos (id bigint generated by default as identity primary key,
        url text unique, titulo text);
      create table public.estado_dos_produtos (produto_id bigint primary key,
        ultimo_avistamento_em date, ofertavel boolean);
      create index estado_produtos_oferta_recente on public.estado_dos_produtos
        (ultimo_avistamento_em desc, produto_id) where ofertavel is true;
      create table public.snapshots (id bigint generated by default as identity primary key,
        produto_id bigint, data date, ofertavel boolean, unique (produto_id, data));
      create table public.produtos (id bigint primary key);`);

    // Inchaço fabricado do mesmo jeito que em produção: reescrita repetida.
    await op.query(`
      insert into public.series_semanais (termo_id, segmento, fonte, semana, valor_bruto, meta)
      select 't' || (n % 200), 'feminino_casual_br', 'busca', date '2026-01-05' + 7 * (n / 200),
             n, jsonb_build_object('x', repeat('m', 300))
      from generate_series(1, 8000) n;
      insert into public.indices_semanais (termo_id, segmento, semana, indice, meta)
      select 't' || (n % 200), 'feminino_casual_br', date '2026-01-05' + 7 * (n / 200), n,
             jsonb_build_object('x', repeat('i', 300))
      from generate_series(1, 4000) n;
      insert into public.artigos (url, titulo)
      select 'https://exemplo.invalid/materia/' || n || '/' || md5(n::text), 'titulo ' || n
      from generate_series(1, 20000) n;
      insert into public.estado_dos_produtos
      select n, date '2026-08-01', true from generate_series(1, 10000) n;
      insert into public.snapshots (produto_id, data, ofertavel)
      select n, date '2026-08-12' + (n % 22), true from generate_series(1, 5000) n;`);
    for (let i = 0; i < 6; i += 1) {
      await op.query('update public.series_semanais set z = coalesce(z, 0) + 1');
      await op.query('update public.indices_semanais set indice = indice + 1');
      await op.query(`update public.estado_dos_produtos
                         set ultimo_avistamento_em = ultimo_avistamento_em + 1`);
    }
    await op.query('update public.artigos set titulo = titulo || \'.\'');
    await op.query('delete from public.artigos where id % 2 = 0');
    await op.query('vacuum public.series_semanais, public.indices_semanais, '
      + 'public.artigos, public.estado_dos_produtos');

    // O log do pg_cron: dono é a plataforma; o operador tem MAINTAIN e DELETE.
    await admin.query(`
      create table cron.job_run_details (runid bigint primary key, jobid bigint,
        status text, command text, return_message text,
        start_time timestamptz, end_time timestamptz);
      alter table cron.job_run_details owner to admin_da_plataforma;
      create table cron.job (jobid bigint, jobname text, schedule text, active boolean);
      alter table cron.job owner to admin_da_plataforma;
      grant select on cron.job to operador;
      grant select, delete on cron.job_run_details to operador;
      insert into cron.job_run_details
      select n, 2, case when n % 50 = 0 then 'failed' else 'succeeded' end,
             'select public.executar_proxima_publicacao_motor();', '1 row',
             now() - (n || ' minutes')::interval, now() - (n || ' minutes')::interval
      from generate_series(1, 30000) n
      -- Nenhuma linha a menos de 10 minutos da fronteira de 7 dias: o ensaio
      -- leva segundos, e uma linha na fronteira mudaria de lado no meio dele.
      where n not between 10070 and 10090;`);

    // 00: inventário roda inteiro em leitura. As consultas 3 e 4 leem
    // tabelas que este ensaio não cria completas; o que se testa aqui é o
    // executor, então o inventário de produção fica para a consulta real.
    const semAcao = passo('70_confere_folga.sql');
    conferir(semAcao.codigo === 0 && /passo sem ação/.test(semAcao.saida),
      '70 roda só leitura e passa com o banco pequeno do laboratório');

    // 11 antes de 10: aborta.
    let r = passo('11_log_do_cron_compactar.sql', '--executar');
    conferir(r.codigo === 1 && /rode o passo 10 antes/.test(r.saida),
      '11 recusa compactar antes de apagar');

    // 10 em ensaio: nada muda.
    const cronAntes = await linhas('cron.job_run_details');
    r = passo('10_log_do_cron_apagar_antigos.sql');
    conferir(r.codigo === 0 && /ENSAIO/.test(r.saida)
      && await linhas('cron.job_run_details') === cronAntes,
      '10 em ensaio não apaga nada');

    // 10 de verdade: só o que passou da retenção.
    r = passo('10_log_do_cron_apagar_antigos.sql', '--executar');
    const esperado = Number((await admin.query(`select count(*) as n from
      generate_series(1, 30000) n where n not between 10070 and 10090 and not (
        (n * interval '1 minute' > interval '7 days' and n % 50 <> 0)
        or n * interval '1 minute' > interval '30 days')`)).rows[0].n);
    const cronDepois = await linhas('cron.job_run_details');
    conferir(r.codigo === 0 && cronDepois === esperado,
      `10 apaga só o que passou da retenção (${cronAntes} -> ${cronDepois})`);

    // 11 sem MAINTAIN: o PostgreSQL pula a tabela com aviso; o executor pega.
    r = passo('11_log_do_cron_compactar.sql', '--executar');
    conferir(r.codigo === 1 && /não encolheu/.test(r.saida),
      '11 sem MAINTAIN falha pela checagem de encolhimento, não em silêncio');

    // 11 com MAINTAIN, como em produção.
    await admin.query('grant maintain on cron.job_run_details to operador');
    const cronTamanho = await tamanho('cron.job_run_details');
    r = passo('11_log_do_cron_compactar.sql', '--executar');
    conferir(r.codigo === 0 && await tamanho('cron.job_run_details') < cronTamanho
      && await linhas('cron.job_run_details') === cronDepois,
      '11 com MAINTAIN devolve espaço e não perde linha');

    // 12 vem desarmado.
    r = passo('12_log_do_cron_truncate_ALTERNATIVA.sql', '--executar');
    conferir(r.codigo === 1 && /desarmada/.test(r.saida)
      && await linhas('cron.job_run_details') === cronDepois,
      '12 (TRUNCATE) recusa sempre até ser armado à mão');

    // Pré-condição do motor.
    await admin.query("insert into public.motor_execucoes (status) values ('running')");
    const serieAntes = await tamanho('public.series_semanais');
    r = passo('50_vacuum_full_series_semanais.sql', '--executar');
    conferir(r.codigo === 1 && /motor em andamento/.test(r.saida)
      && await tamanho('public.series_semanais') === serieAntes,
      '50 aborta com o motor rodando, antes da ação');
    await admin.query("update public.motor_execucoes set status = 'success'");

    // Pré-condição de lock: outra sessão lendo a tabela numa transação aberta.
    const leitor = await conectar('lab');
    await leitor.query('begin');
    await leitor.query('select count(*) from public.series_semanais');
    r = passo('50_vacuum_full_series_semanais.sql', '--executar');
    conferir(r.codigo === 1 && /outra sessao segura lock/.test(r.saida)
      && await tamanho('public.series_semanais') === serieAntes,
      '50 aborta com outra sessão segurando lock, antes da ação');
    await leitor.query('rollback');
    await leitor.end();

    // As ações de verdade: cada alvo encolhe e nenhuma linha some.
    const casos = [
      ['20_reindex_estado_produtos_oferta_recente.sql', 'public.estado_produtos_oferta_recente', 'public.estado_dos_produtos'],
      ['21_reindex_estado_dos_produtos_pkey.sql', 'public.estado_dos_produtos_pkey', 'public.estado_dos_produtos'],
      ['30_vacuum_full_indices_semanais.sql', 'public.indices_semanais', 'public.indices_semanais'],
      ['40_reindex_artigos_url_key.sql', 'public.artigos_url_key', 'public.artigos'],
      ['50_vacuum_full_series_semanais.sql', 'public.series_semanais', 'public.series_semanais'],
    ];
    const snapshots = await linhas('public.snapshots');
    for (const [arquivo, alvo, tabela] of casos) {
      const ensaio = passo(arquivo);
      const antes = await tamanho(alvo);
      const n = await linhas(tabela);
      conferir(ensaio.codigo === 0 && /ENSAIO/.test(ensaio.saida)
        && await tamanho(alvo) === antes, `${arquivo.slice(0, 2)} em ensaio não mexe no alvo`);
      r = passo(arquivo, '--executar');
      const depois = await tamanho(alvo);
      conferir(r.codigo === 0 && depois < antes && await linhas(tabela) === n,
        `${arquivo.slice(0, 2)} encolhe ${alvo} (${antes} -> ${depois}) sem perder linha`);
    }
    conferir(await linhas('public.snapshots') === snapshots,
      'nenhum passo tocou nos snapshots que a A58 precisa');

    // 60 é condicional: com a cota abaixo de 400 MB ele se recusa.
    r = passo('60_vacuum_full_artigos_CONDICIONAL.sql', '--executar');
    conferir(r.codigo === 1 && /nao e necessario/.test(r.saida),
      '60 se recusa quando a folga de 20% já existe');

    // 80: com as funções de produção carregadas, confere; com uma diferente,
    // aborta; com uma faltando, aborta.
    const arquivos = (await readdir(MIGRATIONS)).filter(a => a.endsWith('.sql')
      && a < '20260917200000').sort().reverse();
    const carregar = async (nome) => {
      for (const a of arquivos) {
        const texto = await readFile(path.join(MIGRATIONS, a), 'utf8');
        const i = texto.toLowerCase().lastIndexOf(`create or replace function public.${nome}(`);
        if (i < 0) continue;
        const f = texto.indexOf('$function$;', texto.indexOf('$function$', i) + 10);
        await op.query(texto.slice(i, f + '$function$;'.length));
        return;
      }
    };
    await op.query('create table public.denominador_editorial (fonte text, semana date, total_janela_4sem numeric)');
    for (const nome of ['computar_serie_varejo', 'computar_serie_editorial',
      'computar_z', 'uso_do_banco']) await carregar(nome);
    r = passo('80_confere_antes_das_migrations.sql');
    conferir(r.codigo === 1 && /esperava 5 funcoes e achei 4/.test(r.saida),
      '80 aborta com uma função faltando');
    await carregar('podar_snapshots');
    r = passo('80_confere_antes_das_migrations.sql');
    conferir(r.codigo === 0 && /medidas em 18\/09/.test(r.saida),
      '80 passa com as cinco funções idênticas às de produção');
    await op.query(`create or replace function public.computar_z() returns integer
      language sql as 'select 0'`);
    r = passo('80_confere_antes_das_migrations.sql');
    conferir(r.codigo === 1 && /computar_z mudou desde 18\/09/.test(r.saida),
      '80 aborta quando uma função diverge da medida');

    // 90 roda em leitura e imprime.
    r = passo('90_observacao.sql');
    conferir(r.codigo === 0 && /cota_bytes/.test(r.saida), '90 mede em leitura');

    // A porta do pooler de transação é recusada antes de conectar.
    const recusa = spawnSync(process.execPath, [path.join(AQUI, 'passo.mjs'),
      path.join(AQUI, '90_observacao.sql'), '--host', 'exemplo.invalid',
      '--porta', '6543', '--usuario', 'x', '--senha-vazia'], { encoding: 'utf8' });
    conferir(recusa.status === 1 && /pooler de transação/.test(recusa.stderr),
      'a porta 6543 é recusada');

    await op.end();
  } finally {
    await admin.end().catch(() => {});
    spawnSync(b.pg_ctl, ['stop', '-D', dados, '-m', 'fast', '-w'], { env: AMBIENTE });
    if (servidor.exitCode === null) await once(servidor, 'exit').catch(() => {});
    await rm(raiz, { recursive: true, force: true });
  }
  if (falhas) throw new Error(`${falhas} verificação(ões) falharam`);
  console.log('ROTEIRO VERDE');
}

main().catch(e => { console.error(`FALHOU: ${e.message}`); process.exit(1); });
