-- Fixture do laboratório de capacidade (P21/P22/P24/P25).
--
-- O esquema é o de produção nas colunas que as funções leem e escrevem
-- (conferido em information_schema em 18/09/2026). As FUNÇÕES não estão aqui:
-- o executor as extrai das migrations do repositório e confere o hash contra
-- produção. Este arquivo só monta o chão onde elas pisam.
--
-- As datas são FIXAS, ao contrário do laboratório de significado: nenhuma das
-- funções olha `current_date`, e data fixa torna cada contagem esperada
-- uma conta que dá para fazer de cabeça.

-- Os instrumentos em `lab` leem uma tabela temporaria que so existe em tempo
-- de execucao. `set local` vale so para esta transacao: as migrations
-- aplicadas depois continuam com o corpo das funcoes validado na criacao.
set local check_function_bodies = off;

create role anon nologin;
create role authenticated nologin;
create role service_role nologin;
-- O dono de `uso_do_banco` em produção é `postgres`, que NÃO é superusuário e
-- é membro de `pg_read_all_stats`. Este papel reproduz isso: se a P21 só
-- funcionasse com superusuário, o teste pegaria.
create role dono_como_em_producao nologin in role pg_read_all_stats;

create schema lab;

create table public.termos (
  id text primary key,
  dimensao text not null,
  status text not null default 'aprovado',
  papel text not null default 'atributo'
);

create table public.produtos (
  id bigint primary key,
  segmento text
);

create table public.estado_dos_produtos (
  produto_id bigint primary key references public.produtos(id),
  ultimo_avistamento_em date
);

create table public.snapshots (
  id bigint generated always as identity primary key,
  produto_id bigint not null references public.produtos(id),
  data date not null,
  ofertavel boolean,
  unique (produto_id, data)
);

create table public.produto_termos (
  produto_id bigint not null references public.produtos(id),
  termo_id text not null references public.termos(id),
  primary key (produto_id, termo_id)
);

-- Em produção é uma VIEW sobre `artigos`. Aqui é tabela, para o teste poder
-- mudar o denominador de uma semana só e ver quantas linhas se movem.
create table public.denominador_editorial (
  fonte text,
  semana date,
  total_janela_4sem numeric,
  total_semana_crua numeric
);

create table public.series_semanais (
  id bigint generated by default as identity primary key,
  termo_id text not null,
  segmento text not null,
  fonte text not null,
  semana date not null,
  valor_bruto numeric,
  z numeric,
  n_amostra integer,
  meta jsonb,
  unique (termo_id, segmento, fonte, semana)
) with (fillfactor = 70);

create table public.indices_semanais (
  id bigint generated always as identity primary key,
  termo_id text not null references public.termos(id),
  segmento text not null,
  semana date not null,
  indice numeric,
  estado text check (estado in ('em alta', 'em queda', 'pico', 'estavel')),
  pernas_ativas text[],
  n_pernas integer,
  meta jsonb,
  computado_em timestamptz not null default now(),
  unique (termo_id, segmento, semana)
) with (fillfactor = 70);

-- VAREJO
--
-- 20 produtos no painel, vistos toda segunda de tres semanas. Todos sao
-- vestido; 1-10 sao pretos; 5-12 sao florais. Nove linhas esperadas: tres
-- termos em tres semanas.
insert into public.termos (id, dimensao) values
  ('vestido', 'categoria'), ('preto', 'cor'), ('floral', 'estampa');

insert into public.produtos (id, segmento)
select n, 'feminino_casual_br' from generate_series(1, 20) n;

insert into public.estado_dos_produtos (produto_id, ultimo_avistamento_em)
select n, date '2026-08-30' from generate_series(1, 20) n;

insert into public.snapshots (produto_id, data, ofertavel)
select n, d, true
from generate_series(1, 20) n,
     unnest(array[date '2026-08-10', date '2026-08-17', date '2026-08-24']) d;

insert into public.produto_termos (produto_id, termo_id)
select n, 'vestido' from generate_series(1, 20) n
union all select n, 'preto' from generate_series(1, 10) n
union all select n, 'floral' from generate_series(5, 12) n;

-- EDITORIAL
--
-- O denominador da perna em seis semanas.
insert into public.denominador_editorial (fonte, semana, total_janela_4sem, total_semana_crua)
select 'editorial_br', date '2026-07-27' + 7 * k, 400 + 10 * k, 100 + k
from generate_series(0, 5) k;

-- O que o coletor editorial grava: contagem crua em `valor_bruto`, meta com
-- `coletado_em`. Vestido nas seis semanas; preto so na 3a e na 5a -- as duas
-- que faltam depois da primeira viram zero materializado.
create function lab.semear_editorial() returns void language sql as $$
  insert into public.series_semanais
    (termo_id, segmento, fonte, semana, valor_bruto, z, n_amostra, meta)
  select 'vestido', 'feminino_casual_br', 'editorial_br', date '2026-07-27' + 7 * k,
         c, null::numeric, c,
         jsonb_build_object('janela_semanas', 4, 'contagem_semana_crua', c,
                            'normalizacao', 'pendente: computar_serie_editorial()',
                            'coletado_em', '2026-09-01T10:00:00Z')
  from unnest(array[12, 15, 9, 20, 11, 14]) with ordinality v(c, k1),
       lateral (select (k1 - 1)::int as k) kk
  union all
  select 'preto', 'feminino_casual_br', 'editorial_br', s, c, null::numeric, c,
         jsonb_build_object('janela_semanas', 4, 'contagem_semana_crua', c,
                            'normalizacao', 'pendente: computar_serie_editorial()',
                            'coletado_em', '2026-09-01T10:00:00Z')
  from (values (date '2026-08-10', 10), (date '2026-08-24', 13)) p(s, c);
$$;

-- BUSCA
--
-- Dezesseis semanas para vestido e para preto. O z exige oito semanas de
-- historia na janela (busca), entao cada termo ganha z nas semanas 8 a 15:
-- dezesseis z esperados na primeira escrita.
create function lab.semear_busca() returns void language sql as $$
  insert into public.series_semanais
    (termo_id, segmento, fonte, semana, valor_bruto, z, n_amostra, meta)
  select t, 'feminino_casual_br', 'busca', date '2026-05-11' + 7 * k,
         case t when 'vestido' then 50 + (k * 7) % 11 else 30 + (k * 5) % 7 end,
         null::numeric, null::integer,
         jsonb_build_object('fonte', 'google_trends', 'coletado_em', '2026-09-01T11:00:00Z')
  from unnest(array['vestido', 'preto']) t, generate_series(0, 15) k;
$$;

-- INSTRUMENTOS
--
-- Tres medidas independentes do que foi escrito, porque qualquer uma sozinha
-- pode mentir: o retorno da funcao conta o que ELA acha que escreveu; o
-- contador da transacao conta o que o executor gravou; o `ctid` mostra
-- fisicamente qual linha ganhou versao nova.
create function lab.updates() returns bigint language sql as $$
  select pg_stat_get_xact_tuples_updated('public.series_semanais'::regclass);
$$;

create function lab.inserts() returns bigint language sql as $$
  select pg_stat_get_xact_tuples_inserted('public.series_semanais'::regclass);
$$;

create function lab.fotografar() returns void language plpgsql as $$
begin
  if to_regclass('pg_temp.lab_antes') is not null then
    drop table pg_temp.lab_antes;
  end if;
  create temp table lab_antes as
  select id, ctid::text as versao, valor_bruto, z, n_amostra,
         meta - 'computado_em' as meta_de_negocio,
         meta->>'computado_em' as carimbo
  from public.series_semanais;
end $$;

-- Linhas cujo valor de NEGOCIO mudou desde a foto. `computado_em` fica fora:
-- e carimbo, nao medida.
create function lab.mudadas() returns bigint language sql as $$
  select count(*) from public.series_semanais s
  join pg_temp.lab_antes a using (id)
  where s.valor_bruto is distinct from a.valor_bruto
     or s.z is distinct from a.z
     or s.n_amostra is distinct from a.n_amostra
     or (s.meta - 'computado_em') is distinct from a.meta_de_negocio;
$$;

-- Linhas que ganharam versao fisica nova desde a foto.
create function lab.movidas() returns bigint language sql as $$
  select count(*) from public.series_semanais s
  join pg_temp.lab_antes a using (id)
  where s.ctid::text <> a.versao;
$$;

-- Movidas SEM ter mudado: e o que a P22 existe para zerar.
create function lab.movidas_sem_mudar() returns bigint language sql as $$
  select count(*) from public.series_semanais s
  join pg_temp.lab_antes a using (id)
  where s.ctid::text <> a.versao
    and s.valor_bruto is not distinct from a.valor_bruto
    and s.z is not distinct from a.z
    and s.n_amostra is not distinct from a.n_amostra
     and (s.meta - 'computado_em') is not distinct from a.meta_de_negocio;
$$;

-- Os mesmos tres instrumentos, separados para `indices_semanais`. A P25
-- precisa provar a escrita fisica, e nao apenas confiar no row_count dela.
create function lab.updates_indices() returns bigint language sql as $$
  select pg_stat_get_xact_tuples_updated('public.indices_semanais'::regclass);
$$;

create function lab.inserts_indices() returns bigint language sql as $$
  select pg_stat_get_xact_tuples_inserted('public.indices_semanais'::regclass);
$$;

create function lab.deletes_indices() returns bigint language sql as $$
  select pg_stat_get_xact_tuples_deleted('public.indices_semanais'::regclass);
$$;

create function lab.fotografar_indices() returns void language plpgsql as $$
begin
  if to_regclass('pg_temp.lab_indices_antes') is not null then
    drop table pg_temp.lab_indices_antes;
  end if;
  create temp table lab_indices_antes as
  select id, ctid::text as versao, termo_id, segmento, semana, indice, estado,
         pernas_ativas, n_pernas, meta - 'computado_em' as meta_de_negocio,
         meta->>'computado_em' as carimbo_meta, computado_em as carimbo_coluna
  from public.indices_semanais;
end $$;

create function lab.indices_mudados() returns bigint language sql as $$
  select count(*) from public.indices_semanais i
  join pg_temp.lab_indices_antes a using (id)
  where i.indice is distinct from a.indice
     or i.estado is distinct from a.estado
     or i.pernas_ativas is distinct from a.pernas_ativas
     or i.n_pernas is distinct from a.n_pernas
     or (i.meta - 'computado_em') is distinct from a.meta_de_negocio;
$$;

create function lab.indices_movidos() returns bigint language sql as $$
  select count(*) from public.indices_semanais i
  join pg_temp.lab_indices_antes a using (id)
  where i.ctid::text <> a.versao;
$$;

create function lab.indices_movidos_sem_mudar() returns bigint language sql as $$
  select count(*) from public.indices_semanais i
  join pg_temp.lab_indices_antes a using (id)
  where i.ctid::text <> a.versao
    and i.indice is not distinct from a.indice
    and i.estado is not distinct from a.estado
    and i.pernas_ativas is not distinct from a.pernas_ativas
    and i.n_pernas is not distinct from a.n_pernas
    and (i.meta - 'computado_em') is not distinct from a.meta_de_negocio;
$$;
